#!/usr/bin/env python3
"""Fetch the human-labelled slice of ARIES: reviewer comments and the edits made for them.

    ./fetch.py            # download, filter to human labels, write the corpus
    ./fetch.py --check    # verify the pinned digest, write nothing
    ./fetch.py --update   # print the digest, to re-pin after an upstream change

ARIES pairs peer-review comments with the edits an author actually made to the
paper in response. AI2, public S3, no credentials, ODC-By.

    obligation    a reviewer's comment on a submitted paper
    claim         the author's rebuttal, asserting what they changed
    document      the paper, before and after
    label         which edits, if any, correspond to that comment

WHY THIS ONE AND NOT THE LIVE API. OpenReview itself carries the same shape but
no per-comment resolution: the only signal is a per-REVIEW score delta, which
covers a review raising five separate points with a single number, is absent for
about 80% of reviews, and moves with co-reviewers' scores — so a tool tuned
against it learns reviewer persuasion and social dynamics rather than compliance.
That is a validity failure and more data does not fix it. ARIES has what the API
does not: humans labelled each comment individually.

ONLY THE HUMAN LABELS ARE USED, and this is the important line in the file.
The dataset also ships thousands of synthetic labels generated by matching author
responses that QUOTE the review comment — that is, derived from the claim of
compliance. Scoring a tool on whether a claim is true, against a label built from
that same claim, measures nothing and looks like it measures everything. Rows are
filtered to `annotation == "manual"` and the rest are left alone.

THE LABEL IS ALIGNMENT, NOT ADEQUACY. `positive_edits` means "these edits
correspond to this comment", not "this comment was answered well". Zero aligned
edits is therefore a strong negative — nothing in the revision speaks to the
comment at all. One or more is NOT proof the response was good, and a tool
judging sufficiency still needs its own pass over those.
"""

import argparse
import collections
import csv
import hashlib
import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = "https://ai2-s2-research-public.s3.amazonaws.com/aries"
WANTED = ["edit_labels_train.jsonl", "edit_labels_test.jsonl",
          "review_comments.jsonl"]
PINNED = "b45a56817314bd02"


def lines(name):
    with urllib.request.urlopen(f"{BASE}/{name}", timeout=180) as response:
        body = response.read()
    for line in body.decode("utf-8", "replace").splitlines():
        line = line.strip()
        if line:
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--update", action="store_true")
    args = parser.parse_args()

    print("fetching the label and comment files (~1.8 MB of 327 MB)\n")
    labels, kinds = [], collections.Counter()
    for name in WANTED[:2]:
        for row in lines(name):
            kinds[row.get("annotation", "?")] += 1
            if row.get("annotation") == "manual":
                labels.append(row)
        print(f"  {name}")
    comments = {}
    for row in lines(WANTED[2]):
        if row.get("annotation") == "manual":
            comments[(row["doc_id"], row["comment_id"])] = row
    print(f"  {WANTED[2]}\n")

    print(f"  label rows by annotation: {dict(kinds)}")
    print(f"  keeping only 'manual' — the synthetic labels are derived from the")
    print(f"  author's own response and cannot test whether that response is true\n")

    rows = []
    for label in labels:
        key = (label["doc_id"], label["comment_id"])
        comment = comments.get(key)
        if not comment:
            continue
        aligned = len(label.get("positive_edits") or [])
        rows.append({
            "id": f"{label['doc_id']}-{label['comment_id']}",
            "doc_id": label["doc_id"],
            "comment_id": label["comment_id"],
            "review_id": comment.get("review_id", ""),
            "comment": " ".join((comment.get("comment") or "").split()),
            "aligned_edits": aligned,
            "verdict": "addressed" if aligned else "not_addressed",
            "split": label.get("split", ""),
        })

    if not rows:
        sys.exit("no human-labelled rows found — the upstream schema may have moved")

    material = "\n".join(f"{r['id']}|{r['verdict']}"
                         for r in sorted(rows, key=lambda r: r["id"]))
    got = hashlib.sha256(material.encode()).hexdigest()
    if args.update:
        print(f"digest: {got[:16]}")
        return 0
    if not got.startswith(PINNED):
        print(f"DIGEST MISMATCH\n  pinned {PINNED}\n  now    {got[:16]}\n"
              f"\nThe upstream corpus has changed. Read the labels before trusting"
              f"\nthem, then re-pin with --update.", file=sys.stderr)
        if args.check:
            return 1
    elif args.check:
        print(f"digest {got[:16]} matches the pin")
        return 0

    with open(os.path.join(HERE, "comments.csv"), "w", newline="",
              encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    spread = collections.Counter(r["verdict"] for r in rows)
    papers = len({r["doc_id"] for r in rows})
    negative = 100 * spread["not_addressed"] / len(rows)
    with open(os.path.join(HERE, "labels.json"), "w", encoding="utf-8") as handle:
        json.dump({"digest": got[:16], "source": "ARIES, human-labelled subset only",
                   "licence": "ODC-By", "comments": len(rows), "papers": papers,
                   "spread": dict(spread),
                   "negative_share": round(negative, 1),
                   "excluded_synthetic": kinds.get("synthetic", 0) + kinds.get("auto", 0),
                   "caution": ("positive_edits means edits CORRESPOND to the comment, "
                               "not that the comment was answered adequately. Zero is a "
                               "strong negative; non-zero is not a strong positive.")},
                  handle, indent=1)

    print(f"  {len(rows)} human-labelled comments across {papers} papers")
    for verdict, count in spread.most_common():
        print(f"    {verdict:<16} {count}")
    print(f"\n  negative share: {negative:.0f}%")
    print("\nwrote comments.csv and labels.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
