#!/usr/bin/env python3
"""Fetch and convert the CM-1 requirements-tracing dataset.

CM-1 is a NASA scientific instrument, published through the CoEST traceability
community: 22 high-level requirements, 53 design elements, and a hand-built
answer matrix of 45 true links out of 1,166 candidate pairs.

Why it matters here: **retrieval has never been measured against ground truth.**
Every precision and recall number in this project so far is end to end, so a
retrieval miss and a judgement error are indistinguishable. CM-1 separates them.
Its source artefacts are already atomic "shall" statements with stable IDs, so
extraction is out of the picture too — what remains is exactly the question
"given this requirement, does the retriever surface the passages that bear on
it?"

    ./fetch.py            # download, verify, convert
    ./fetch.py --force

Writes source/requirements.md, source/design.md and answers.yaml. Nothing is
committed: the archive is fetched from its publisher and the licence and
citation obligations stay there.

Data courtesy of NASA, collated by Jane Huffman Hayes. If you publish anything
using it, cite:

    Jane Huffman Hayes, Alex Dekhtyar, Senthil Karthikeyan Sundaram.
    "Advancing Candidate Link Generation for Requirements Tracing: The Study of
    Methods." IEEE Trans. Software Eng. 32(1): 4-19 (2006)
"""

import argparse
import collections
import hashlib
import os
import sys
import urllib.request
import zipfile
from xml.etree import ElementTree as ET

URL = "http://sarec.nd.edu/coest/datasets/CM1-NASA.zip"
ARCHIVE_SHA256 = "b7838320a869a674d9a28c47d6d01c2478d3557c1dc4d7c562136b1b9a2827ba"
HERE = os.path.dirname(os.path.abspath(__file__))


def artifacts(archive, name):
    root = ET.fromstring(archive.read(name).decode("utf-8-sig"))
    out = {}
    for node in root.iter("artifact"):
        identifier = (node.findtext("id") or "").strip()
        content = " ".join((node.findtext("content") or "").split())
        if identifier and content:
            out[identifier] = content
    return out


def write_document(path, title, note, items):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(f"# {title}\n\n{note}\n\n")
        for identifier, content in items.items():
            handle.write(f"## {identifier}\n\n{content}\n\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--update", action="store_true",
                        help="print the archive hash to pin")
    args = parser.parse_args()

    out_dir = os.path.join(HERE, "source")
    os.makedirs(out_dir, exist_ok=True)
    archive_path = os.path.join(out_dir, "CM1-NASA.zip")

    if not os.path.exists(archive_path) or args.force or args.update:
        try:
            with urllib.request.urlopen(URL, timeout=90) as response:
                data = response.read()
        except Exception as exc:                            # noqa: BLE001
            sys.exit(f"download failed: {exc}\n  {URL}")
        with open(archive_path, "wb") as handle:
            handle.write(data)
    data = open(archive_path, "rb").read()

    digest = hashlib.sha256(data).hexdigest()
    if ARCHIVE_SHA256 and digest != ARCHIVE_SHA256 and not args.update:
        sys.exit(f"archive hash mismatch\n  pinned {ARCHIVE_SHA256}\n  actual {digest}")
    if args.update:
        print(f"ARCHIVE_SHA256 = \"{digest}\"")

    archive = zipfile.ZipFile(archive_path)
    source = artifacts(archive, "CM1-sourceArtifacts.xml")
    target = artifacts(archive, "CM1-targetArtifacts.xml")

    links = collections.defaultdict(list)
    root = ET.fromstring(archive.read("CM1-answerSet.xml").decode("utf-8-sig"))
    for node in root.iter("link"):
        links[(node.findtext("source_artifact_id") or "").strip()].append(
            (node.findtext("target_artifact_id") or "").strip())

    write_document(os.path.join(out_dir, "requirements.md"),
                   "CM-1 high-level requirements",
                   "NASA scientific instrument. One heading per requirement; the "
                   "text is already an atomic obligation.", source)
    write_document(os.path.join(out_dir, "design.md"),
                   "CM-1 design elements",
                   "One heading per design element, so a retrieval chunk "
                   "corresponds to exactly one artefact.", target)

    unlinked = sorted(set(source) - set(links))
    with open(os.path.join(HERE, "answers.yaml"), "w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by fetch.py from CM1-answerSet.xml — do not edit.\n"
            "#\n"
            "# gold[requirement] = design elements a human tracer linked to it.\n"
            "# A link means 'bears on', not 'discharges' — so this measures\n"
            "# RETRIEVAL cleanly and coverage judgement only indirectly.\n"
            f"#\n# requirements {len(source)}, design elements {len(target)}, "
            f"links {sum(len(v) for v in links.values())}, "
            f"candidate pairs {len(source)*len(target)}\n\n")
        handle.write("gold:\n")
        for identifier in sorted(source):
            targets = sorted(links.get(identifier, []))
            handle.write(f"  {identifier}: [{', '.join(targets)}]\n")
        handle.write("\n# Requirements no design element traces to. In coverage "
                     "terms these are\n# the only ones that should read unmet.\n")
        handle.write("unlinked: [" + ", ".join(unlinked) + "]\n")

    print(f"  requirements     {len(source)}")
    print(f"  design elements  {len(target)}")
    print(f"  gold links       {sum(len(v) for v in links.values())} "
          f"across {len(links)} requirements")
    print(f"  unlinked         {len(unlinked)}  {unlinked}")
    print(f"  wrote source/requirements.md, source/design.md, answers.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
