#!/usr/bin/env python3
"""Turn the fetched slice into a dossier project the real tools can run against.

    ./fetch.py && ./build-corpus.py && \
        dossier freeze fixtures/ntsb

WHY THIS SHAPE. The toolkit's question is "does this document, as it stands,
satisfy this comment". NTSB's records are the same question wearing different
words: the recommendation is the comment, and the addressee's letter is the text
that either satisfies it or does not. So the claims become one document — one
section per recommendation — and the recommendations become the register.

Putting ALL the claims in one document rather than running each pair in isolation
is deliberate, and it makes the test harder rather than easier. The tool has to
find the passage that answers a given recommendation among twenty-five that look
alike, written by one addressee, on one subject, in one decade. Handing it a
single claim and asking "does this satisfy that" would measure the model's
reading and nothing about retrieval or locating, which is most of what the
toolkit does.

WHAT IS DELIBERATELY NOT HERE. NTSB's own correspondence. It contains the
adjudication, and a document carrying the answer measures nothing. fetch.py
already excludes it; this is the second place that fact matters, so it is written
down in both.
"""

import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    source = os.path.join(HERE, "recommendations.csv")
    if not os.path.exists(source):
        sys.exit("no recommendations.csv — run ./fetch.py first")
    rows = list(csv.DictReader(open(source, encoding="utf-8")))

    # The document: what the addressee says it did, one section per record.
    lines = ["# Addressee responses to safety recommendations", "",
             "Each section is the addressee's own account of what it did. Nothing",
             "here is a ruling on whether that was enough.", ""]
    for row in rows:
        lines += [f"## {row['id']} — {row['addressee']}", ""]
        for paragraph in row["claim"].split("\n"):
            if paragraph.strip():
                lines += [paragraph.strip(), ""]
    with open(os.path.join(HERE, "claims.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")

    # The register: one recommendation per row, in the shape matrix tools read.
    with open(os.path.join(HERE, "obligations.csv"), "w", newline="",
              encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["id", "addressee", "obligation"])
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row[k] for k in writer.fieldnames})

    with open(os.path.join(HERE, "corpus.yaml"), "w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by build-corpus.py from the fetched slice. The claims are\n"
            "# the draft: they are the text under judgement. There is no anchor and\n"
            "# no requirements document — NTSB tracks correspondence, not redlines,\n"
            "# which is the known weakness the README states.\n"
            "documents:\n"
            "  - path: claims.md\n"
            "    slug: claims\n"
            "    role: draft\n")

    print(f"  claims.md        {len(lines):,} lines, "
          f"{sum(len(l) for l in lines):,} chars, {len(rows)} sections")
    print(f"  obligations.csv  {len(rows)} rows")
    print(f"  corpus.yaml      1 document (claims, role draft)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
